export const content = {
    '404Header': '404',
    '404Message': 'The page you\'re looking for does not exist (anymore).',
    '404Title': 'Page not found',
    Back: 'Back',
    Banner: 'Banner',
    Filter: 'Filter',
    FilterTags: 'Select tags to show',
    Loading: 'Loading...',
    More: 'More',
    MorePosts: 'More posts',
    MoreBooksVideos: 'More books and videos',
    NextPost: 'Next post: ',
    NextRecommendation: 'Next recommendation: ',
    NoOptionsSelect: 'No further tags available',
    Ok: 'Ok',
    PreviousPost: 'Previous post: ',
    PreviousRecommendation: 'Previous recommendation: ',
    ShowAll: 'Show all'
};
