export const content = {
    '404Header': '404',
    '404Message': 'The page you\'re looking for does not exist (anymore).',
    '404Title': 'Page not found',
    AllRightsReserved: 'All rights reserved.',
    Back: 'Back',
    Backto: 'Back to overview',
    BacktoRecommended: 'Back to recommendations',
    Banner: 'Banner',
    Blog: 'Blog',
    Business: 'Business name',
    Continue: 'Continue',
    Copy: 'Copy',
    Email: 'Email',
    EmailErrorMessage: 'Enter a valid email address',
    Filter: 'Filter',
    FilterTags: 'Select tags to show',
    InterestedIn: 'I\'m interested in:',
    Loading: 'Loading...',
    MailSendFailed: 'Something went wrong, please try again or email me directly at ',
    MailSendSuccess: 'Thank you for sending this message. I\'ll get back to you as soon as I can.',
    Name: 'Name',
    NameErrorMessage: 'Please enter a name',
    NextPost: 'Next post: ',
    NextRecommendation: 'Next recommendation: ',
    NoOptionsSelect: 'No further tags available',
    Ok: 'Ok',
    PreviousPost: 'Previous post: ',
    PreviousRecommendation: 'Previous recommendation: ',
    SelectedTags: 'Selected tags',
    SendEmail: 'Send me an email',
    SendEmailDone: 'Thank you for your enquiry',
    ShowAll: 'Show all',
    ShowModal: 'Show more',
    ShowModalMessage: 'This website does not work properly in your current browser.',
    Submit: 'Submit',
    TextBox: 'Questions / other',
    TryAgain: 'Try again',
    UnsupportedContinue: 'Press continue to view this site anyway.',
    UnsupportedMessage: 'This website does not work properly in your current browser. Use one of the browser below for the best experience.',
    UnsupportedTitle: 'Browser not supported',
    WebDesign: 'Website design',
    WebHosting: 'Website hosting'
};
export const metaData = {
    AboutDescription: 'About',
    AboutImage: '/images/banner-blog-default.png',
    AboutTitle: 'About',
    AuthorName: `Joep van de Laarschot`,
    BusinessName: 'Joeplaa blog',
    ContactTitle: 'Contact',
    FirstName: 'Joep',
    LastName: 'van de Laarschot',
    BlogDescription: '',
    BlogImage: '/images/banner-blog-default.png',
    BlogTitle: 'Blog',
    BlogSubtitle: '',
    PageTitle: 'joeplaa blog',
    RecommendedDescription: 'I\'ve read a lot of books and watched countless videos on the web. Here you can find a list of my recommended books and videos.',
    RecommendedImage: '/images/banner-blog-recommended.png',
    RecommendedTitle: 'Recommended',
    SiteDescription: 'Helping people create their digital home.',
    SiteImage: `/images/banner-www-default.png`,
    SiteLanguage: `en-US`,
    SiteLocale: `en_us`,
    SiteName: 'joeplaa blog',
    SiteTitle: 'joeplaa blog',
    SiteUrl: process.env.GATSBY_BLOG_URL,
    TitleSeparator: '|',
    TitleTemplate: 'joeplaa blog',
    TwitterUsername: ''
}
export const navigation = {
    about: '/about',
    blog: '/blog',
    contact: process.env.GATSBY_URL + '/home#Contact',
    portfolio: process.env.GATSBY_URL + '/portfolio',
    recommended: '/recommended'
}
export const settings = {
    breakpoint: 'lg',
    dateFormat: 'LLLL d, yyyy',
    iconSize: '40px'
}
export const urls = {
    email: 'info@joeplaa.com',
    facebook: 'https://www.facebook.com/joeplaa',
    github: 'https://github.com/joeplaa',
    instagram: 'https://www.instagram.com/joeplaa/',
    linkedin: 'https://www.linkedin.com/in/joeplaa/',
    umami: 'https://umami.joeplaa.com/umami.js'
}